name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build Image and push to Docker Hub

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            saltydk/v-rising:latest
            saltydk/v-rising:${{ steps.vars.outputs.sha_short }}
